server:
  port: 8000
spring:
  application:
    name: productservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product
      username: product
      password: product
      authentication-database: admin