server:
  port: 8000
spring:
  application:
    name: productservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product
      username: product
      password: product
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

#product:
#  images:
#    upload-dir=/path/to/upload/directory: