server:
  port: 8000
spring:
  application:
    name: "products"
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8071/"

  data:
    mongodb:
      host: localhost
      port: 27017
      database: product
      username: product
      password: product
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

management:
  endpoints:
    web:
      exposure:
        include: "*"