server:
  port: 8000
spring:
  application:
    name: productservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product
      username: product
      password: product
      authentication-database: admin
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

product:
  images:
    upload-dir=/path/to/upload/directory: