version: "3.8"
services:
  DB_PRODUCT:
    container_name: toko_online_product_DB
    image: mongo:6.0-jammy
    restart: always
    shm_size: 256mb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=product
      - MONGO_INITDB_ROOT_PASSWORD=product
      - MONGO_INITDB_DATABASE=product
    volumes:
      - product_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - toko_online
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M

  REDIS_PRODUCT:
    container_name: toko_online_redis_product_DB
    image: redis:6.2
    restart: always
    shm_size: 256mb
    ports:
      - "6370:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - toko_online
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M



  DB_CART:
    container_name: toko_online_cart_DB
    image: postgres:16-alpine
    restart: always
    shm_size: 256mb
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=cart
      - POSTGRES_USER=cart
      - POSTGRES_DB=cart
    volumes:
      - cart_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - toko_online
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M

  DB_ORDER:
    container_name: toko_online_order_DB
    image: postgres:16-alpine
    restart: always
    shm_size: 256mb
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=order
      - POSTGRES_USER=order
      - POSTGRES_DB=order
    volumes:
      - order_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - toko_online
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M

  DB_USER:
    container_name: toko_online_user_DB
    image: postgres:14-alpine
    restart: always
    shm_size: 256mb
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=user
    volumes:
      - user_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - toko_online
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M

  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - toko_online
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    ports:
      - "7000:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - toko_online
 

volumes:
  product_data:
  order_data:
  user_data:
  cart_data:
  redis_data:
  keycloak_data:

networks:
  toko_online:
    name: "toko_online"
    driver: "bridge"








