version: "3.8"
services:
  DB_PRODUCT:
    container_name: toko_online_product_DB
    image: mongo:6.0-jammy
    restart: always
    shm_size: 256mb
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M
    environment:
      - MONGO_INITDB_ROOT_USERNAME=product
      - MONGO_INITDB_ROOT_PASSWORD=product
      - MONGO_INITDB_DATABASE=product
    volumes:
      - product_data:/data/db

  REDIS_PRODUCT:
    container_name: toko_online_redis_product_DB
    image: redis:6.2
    restart: always
    shm_size: 256mb
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=yourpassword
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M


  DB_CART:
    container_name: toko_online_cart_DB
    image: postgres:16-alpine
    restart: always
    shm_size: 256mb
    ports:
      - "5435:5432"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M
    environment:
      - POSTGRES_PASSWORD=cart
      - POSTGRES_USER=cart
      - POSTGRES_DB=cart
    volumes:
      - cart_data:/var/lib/postgresql/data

  DB_ORDER:
    container_name: toko_online_order_DB
    image: postgres:16-alpine
    restart: always
    shm_size: 256mb
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M
    environment:
      - POSTGRES_PASSWORD=order
      - POSTGRES_USER=order
      - POSTGRES_DB=order
    volumes:
      - order_data:/var/lib/postgresql/data

  DB_USER:
    container_name: toko_online_user_DB
    image: postgres:14-alpine
    restart: always
    shm_size: 256mb
    ports:
      - "5434:5432"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=user
    volumes:
      - user_data:/var/lib/postgresql/data

volumes:
  product_data:
  order_data:
  user_data:
  cart_data: