server:
  port: 8001
spring:
  application:
    name: "users"
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8071"
  datasource:
    url: jdbc:postgresql://localhost:5434/user
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  cloud:
    function:
      definition: updateCommunication
#      kalau function lebih dari satu, dan independen arti nya kira kirim atau terima masing2 tidak barengan
#    definition: updateCommunication; sendXX, funcAAa
    stream:
      bindings:
        updateCommunication-in-0:
          destination: communication-sent
          group: ${spring.application.name}
        sendCommunication-out-0:
          destination: send-communication
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

info:
  app:
    name: "users"
    description: "Toko online users Application"
    version: "1.0.0"