server:
  port: 8001
spring:
  application:
    name: "users"
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8071"
  datasource:
    url: jdbc:postgresql://localhost:5434/user
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

management:
  endpoints:
    web:
      exposure:
        include: "*"