server:
  port: 8001
spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5434/user
    username: user
    password: user
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect