server:
  port: 8003
spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:postgresql://localhost:5433/order
    username: order
    password: order
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
