server:
  port: 8003
spring:
  application:
    name: "orders"
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:postgresql://localhost:5433/order
    username: order
    password: order

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
