version: '3'
services:
  eureka-server:
    image: robi290899/eurekaserver
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - toko-online

  config-server:
    image: robi290899/configserver
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - toko-online
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  product-service:
    image: robi290899/productservice
    container_name: product-service
    ports:
      - "8000:8000"
    networks:
      - toko-online
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

networks:
  toko-online:
    driver: bridge
